/**********************************************************************
 *                                                                    *
 *       This file was auto-generated by the adc_conf.pl script       *
 *                                                                    *
 *                      from zephyr/dts/adc.dtsi                      *
 *                                                                    *
 **********************************************************************/
/*
 * Copyright (c) 2021 Centre National de la Recherche Scientifique
 *
 * CNRS, établissement public à caractère scientifique et technologique,
 * dont le siège est situé 3 rue Michel-Ange, 75794 Paris cedex 16.
 *
 *            Luiz Villa - Projet OwnTech <owntech@laas.fr>
 *        Laboratoire d'analyse et d'architecture des systèmes
 *               LAAS-CNRS - 7, avenue du Colonel Roche
 *                 BP 54200 - 31031 Toulouse cedex 4
 *
 * SPDX-License-Identifier: CECILL-C
 */

/**
 * @file
 * @brief   ADC inputs enumeration generated from devicetree
 *
 * @author  Hugues Larrive <hugues.larrive@laas.fr>
 */

#ifndef ADC_ENUM_H
#define ADC_ENUM_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief   Devicetree ADC inputs
 */
typedef enum {
    V1_LOW,
    I1_LOW,
    V2_LOW,
    I2_LOW,
    V_HIGH,
    I_HIGH,
    TEMP,
    TEMP_MCU,
    VREF_MCU,
} dt_adc_input_t;

#define NUM_ADC_INPUTS  (9)

#ifdef __cplusplus
}
#endif

#endif /* ADC_ENUM_H */
